name: WAV format check

on:
  pull_request:
    branches:
      - master

jobs:
  wav-format-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: List added files
      run: git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
    
    - name: WAV format check
      run: |
        CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -E '^(flags-archive/)')
        if [ -z "$CHANGED_FILES" ]; then
          echo "No files modified in flags-archive/. Skipping validation check."
          exit 0
        fi
        sudo apt-get install --no-install-recommends libimage-exiftool-perl -y
        ./qa/wav-format-check $CHANGED_FILES
